workflows:
  ios-app-store-release:
    name: Flutter iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: CD-Manager
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fixsathi.fixsathi
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing profiles
        script: |
          xcode-project use-profiles
      - name: Clean Project and Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Install and Update Robust CocoaPods
        script: |
          cd ios
          pod cache clean --all
          rm -rf Pods Podfile.lock
          pod repo update
          # --repo-update फ़्लैग के साथ पॉड्स इंस्टॉल करें
          pod install --repo-update
      - name: Flutter build ipa with Pods preference
        script: |
          flutter build ipa --release --no-pub \
            --build-name=1.7.0 \
            --build-number=$(($BUILD_NUMBER)) \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Build versioning
        script: |
            cd ios
            agvtool new-version -all $(($BUILD_NUMBER))
      
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - sukhdeepsinghbham@gmail.com
          - satnamdass25@gmail.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # beta_groups:
        #   - group name 1
        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false