org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# Kotlin compiler
kotlin.incremental=true
kotlin.daemon.enabled=true
# Gradle daemon ON (for faster builds)
org.gradle.daemon=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
# Flutter obfuscation (release builds)
extra-gen-snapshot-options=--obfuscate