// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SE_IymkBcOTHKDQniKqhnUdR6U_J7GQ',
    appId: '1:988141056194:android:f234c705e84ccbfe6c4b5b',
    messagingSenderId: '988141056194',
    projectId: 'fixsathi-80116',
    storageBucket: 'fixsathi-80116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacPrOv36UF5wPgn-Ae9HLgd3nC7IQIPA',
    appId: '1:988141056194:ios:336b77dc8ed9a9096c4b5b',
    messagingSenderId: '988141056194',
    projectId: 'fixsathi-80116',
    storageBucket: 'fixsathi-80116.firebasestorage.app',
    iosClientId: '988141056194-rpan3fbgi5rsfvoatmiuqdpvkaohm1r0.apps.googleusercontent.com',
    iosBundleId: 'com.fixsathi.fixsathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDacPrOv36UF5wPgn-Ae9HLgd3nC7IQIPA',
    appId: '1:988141056194:ios:336b77dc8ed9a9096c4b5b',
    messagingSenderId: '988141056194',
    projectId: 'fixsathi-80116',
    storageBucket: 'fixsathi-80116.firebasestorage.app',
    iosClientId: '988141056194-rpan3fbgi5rsfvoatmiuqdpvkaohm1r0.apps.googleusercontent.com',
    iosBundleId: 'com.fixsathi.fixsathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiGiE6Wt6VEW-yZpggejxHLoLlID-ZuxE',
    appId: '1:988141056194:web:a2fb41aa15b299276c4b5b',
    messagingSenderId: '988141056194',
    projectId: 'fixsathi-80116',
    authDomain: 'fixsathi-80116.firebaseapp.com',
    storageBucket: 'fixsathi-80116.firebasestorage.app',
    measurementId: 'G-6H8NBN0LLV',
  );

}